const colors = {
  light: {
    text: "#fafafa",
    tint: "#7C5CFF",
    background: "#0a0a0a",
    foreground: "#fafafa",
    card: "#141414",
    cardForeground: "#fafafa",
    primary: "#7C5CFF",
    primaryForeground: "#ffffff",
    secondary: "#1a1a1a",
    secondaryForeground: "#fafafa",
    muted: "#1a1a1a",
    mutedForeground: "#71717a",
    accent: "#7C5CFF",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#222222",
    input: "#1e1e1e",
    purple: "#7C5CFF",
    green: "#22c55e",
    pink: "#ec4899",
    amber: "#f59e0b",
    cyan: "#06b6d4",
  },
  dark: {
    text: "#fafafa",
    tint: "#7C5CFF",
    background: "#0a0a0a",
    foreground: "#fafafa",
    card: "#141414",
    cardForeground: "#fafafa",
    primary: "#7C5CFF",
    primaryForeground: "#ffffff",
    secondary: "#1a1a1a",
    secondaryForeground: "#fafafa",
    muted: "#1a1a1a",
    mutedForeground: "#71717a",
    accent: "#7C5CFF",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#222222",
    input: "#1e1e1e",
    purple: "#7C5CFF",
    green: "#22c55e",
    pink: "#ec4899",
    amber: "#f59e0b",
    cyan: "#06b6d4",
  },
  radius: 12,
};

export default colors;
